### PR TITLE
Adding"-server" to mysql-server package name

### PR DESCRIPTION
**Pull request by TheJohnSub**

### CODE REVIEW

**Comment by mattmakai** [comment]
hmm @TheJohnSub is the `-server` necessary? I believe in 16.04 LTS the `mysql` works fine. Perhaps it's an alias for `mysql-server`?

**Comment by TheJohnSub** [comment]
Hm, I ran it on 16.04 when I made this pull request, and it couldn't find the package until I added the server part. Either way, it was easy enough to figure out through your description before the command.

**Comment by mattmakai** [comment]
you're right, i just tried it and it's not correct in the blog post, thank you for catching this!

**Comment by mattmakai** [comment]
this is now live, thanks @TheJohnSub!

**Comment by TheJohnSub** [comment]
no problem, glad to help! thanks for the great post!

**Pull request merged**
