### PR TITLE
Remove bad links as of 2019-12-11

### PR DESCRIPTION
**Pull request by huangsam**

### CODE REVIEW

**Comment by huangsam** [comment]
Feel free to check if everything is correct. I tried to be as fair as I could to the content that was removed and replaced where applicable. Let me know if you have any questions or concerns.

**Comment by huangsam** [comment]
Just went ahead and resolved the recent merge conflicts

**Comment by mattmakai** [comment]
this is actually a coincidence, i used a different tool to find some bad links earlier this week. will merge this now

**Comment by mattmakai** [comment]
thank you so much as always @huangsam! hope to see you at PyCon in 2020

**Pull request merged**
